### ISSUE TITLE
HighCharts 6.0.4 webjar does not contain HighStock or HighMaps

### ISSUE THREAD

**Issue by markot6** [webjars/highcharts#41]
Beginning with release 6.0.4, HighStock and HighMaps have been included in the HighCharts release, i.e. there are no separate tags for these two components. Please rebuild the HighCharts 6.0.4 webjar from [https://github.com/highcharts/highcharts-dist/releases/tag/v6.0.4](url) to include them.

**Comment by jamesward** [comment]
Resolved by: https://github.com/webjars/highcharts/commit/e4a838823025fb32373204dffeeb7e6b55204af0
