### ISSUE TITLE
Deploy highcharts-react-official webjar?

### ISSUE THREAD

**Issue by metametadata** [webjars/highcharts#56]
Hi, I'm not sure if it's the right place to ask, but is there any chance you could also create a webjar for `highcharts-react-official`? Thanks.

**Comment by jamesward** [comment]
Are you looking for a Classic WebJar or will an NPM WebJar be ok?  For NPM you can try to deploy it yourself: https://www.webjars.org/  Click "Add a WebJar"

Let me know.  Thanks!

**Comment by metametadata** [comment]
I suppose Classic one, because deploying NPM one from GUI fails due to the custom license the library has. Deploy log:

```
Starting Deploy
Got package info for org.webjars.npm highcharts-react-official 2.1.3
Determining dependency graph
No dependencies.
Resolving licenses & dependencies for org.webjars.npm highcharts-react-official 2.1.3
All attempts to determine an acceptable license have been exhausted.  The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/highcharts/highcharts-react.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: SEE LICENSE IN 
This problem will likely need to be resolved by working with the library maintainers directly.
```

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/highcharts-react

This will be released shortly.

**Comment by metametadata** [comment]
Thank you!
