### ISSUE TITLE
release 8.2.2

### ISSUE THREAD

**Issue by mcroba** [webjars/highcharts#63]
Could you please release the v8.2.2?

Thank you in advance

**Comment by mcroba** [comment]
Thank you again @jamesward

**Comment by mcroba** [comment]
Sorry @jamesward but any idea why it's not available?
https://www.webjars.org/
or
https://search.maven.org/

**Comment by jamesward** [comment]
Looks like Maven Central had an issue.  Trying again...

**Comment by mcroba** [comment]
All good now, thank you @jamesward
